### ISSUE TITLE
ERROR: LoadError: TaskFailedException

### ISSUE THREAD

**Issue by songofbin** [GuoBioinfoLab/CATT#16]
I am experiencing a problem with the git-installed CATT resource folder. How to fix it ?

$ catt -f testSample.fq -o testSampleOutput -t 2
[bwa_index] Pack FASTA... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.01 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.00 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index ./resource/TR/hs/TRBV.fa
[main] Real time: 0.322 sec; CPU: 0.015 sec
[bwa_index] Pack FASTA... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.00 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.00 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index ./resource/TR/hs/TRBJ.fa
[main] Real time: 0.305 sec; CPU: 0.004 sec
[ Info: 2023-09-26 15:41:18] Program start
[ Info: 2023-09-26 15:41:19] Handing Single-end sample: testSample.fq
[ Info: 2023-09-26 15:41:19] Aligning
ERROR: LoadError: TaskFailedException

    nested task error: failed processes:
      Process(`/path/to/samtools sort -O SAM -t AS -l 0 -@ 4`, ProcessSignaled(13)) [0]
      Process(`/path/to/samtools view -F 2308`, ProcessSignaled(13)) [0]
      Process(`tail -r`, ProcessExited(1)) [1]
      Process(`/path/to/samtools view -h -T /path/to/CATT/resource/TR/hs/TRB/TRBV-gai6-DNA.fa`, ProcessExited(1)) [1]
    
    Stacktrace:
     [1] pipeline_error(procs::Base.ProcessChain)
       @ Base ./process.jl:578
     [2] run(::Base.CmdRedirect; wait::Bool)
       @ Base ./process.jl:480
     [3] run
       @ ./process.jl:477 [inlined]
     [4] map2align(input_file::String, ref::String, fasta_flag::Cmd, prefix::String, threads::Int64, score::Int64)
       @ Main /path/to/CATT/catt.jl:43
     [5] (::var"#93#95"{Dict{String, Any}, Vector{Any}, Cmd, String, Int64})()
       @ Main ./task.jl:514

...and 1 more exception.

Stacktrace:
 [1] sync_end(c::Channel{Any})
   @ Base ./task.jl:445
 [2] macro expansion
   @ ./task.jl:477 [inlined]
 [3] input_convert(args::Dict{String, Any}, input_file::String; input_file2::Nothing)
   @ Main /path/to/CATT/catt.jl:143
 [4] input_convert(args::Dict{String, Any}, input_file::String)
   @ Main /path/to/CATT/catt.jl:134
 [5] proc(args::Dict{String, Any})
   @ Main /path/to/CATT/catt.jl:767
 [6] top-level scope
   @ /path/to/CATT/catt.jl:785
in expression starting at /path/to/CATT/catt.jl:784

**Comment by aqzas** [comment]
sorry for the late reply.
Based on the debug information, you need to change the samtools path in  `reference.jl`
It seems that the format of README file is broken, which have been fixed. You can find the instructions in it.

**Comment by songofbin** [comment]
谢谢答复。

根据报错信息“ Process(`tail -r`, ProcessExited(1)) [1]”，发现出错的是“tail -r”。推测tail的-r参数与系统有关，Ubuntu似乎不支持这个参数。

注释掉这一行，可以继续运行，但从Extending这一步开始，仍有报错，信息如下：

[ Info: 2023-10-10 10:34:53] Extending
ERROR: LoadError: TaskFailedException

    nested task error: AssertionError: Multiple concurrent writes to Dict detected!

综上，catt测试失败。希望能够看看怎么解决，谢谢。

**Comment by aqzas** [comment]
@songofbin 

ubuntu 系统可以把 tail -r 换成 tac, 文件里面的已经改过来了
