### ISSUE TITLE
Help running with paired end reads

### ISSUE THREAD

**Issue by JFavaloro** [GuoBioinfoLab/CATT#5]
Hi,

Very eager to try this out! Apologies in advance; I'm a beginner.

I've managed to get the docker image running and can successfully run the testSample.fq

I'm now trying to run my own data which is paired end and am getting a load error.

Here's what I'm running:

docker run -it --rm -v $PWD:/output -w /output -u $UID guobioinfolab/catt \
> catt --f1 /Users/XXX/Documents/CATT/PT1_S5_L001_R1_001.fastq --f2 /Users/XXX/Documents/CATT/PT1_S5_L001_R2_001.fastq -o PT1

Here's the output:

[ Info: 2020-06-30 23:13:01] Program start
[ Info: 2020-06-30 23:13:02] Handing Paired-end sample: /Users/XXX/Documents/CATT/PT1_S5_L001_R1_001.fastq
[ Info: 2020-06-30 23:13:02] Aligning
ERROR: LoadError: failed process: Process(`/home/feifei/bwa-0.7.17/bwa mem -v 1 -t 4 -k 8 -A 1 -B 2 -L 0 -T 12 /home/feifei/resource/TR/hs/TRB/TRBV-gai6-DNA.fa /Users/XXX/Documents/CATT/PT1_S5_L001_R1_001.fastq`, ProcessExited(1)) [1]
error(::String, ::Base.Process, ::String, ::Int64, ::String) at ./error.jl:42
pipeline_error at ./process.jl:785 [inlined]
pipeline_error(::Base.ProcessChain) at ./process.jl:798
#run#515(::Bool, ::Function, ::Base.CmdRedirect) at ./process.jl:726
run at ./process.jl:724 [inlined]
map2align(::String, ::String, ::Cmd, ::String, ::Int64, ::Int64) at /home/feifei/catt.jl:39
(::getfield(Main, Symbol("##99#101")){Dict{String,Any}})() at ./task.jl:259

...and 3 more exception(s).

Stacktrace:
 [1] sync_end(::Array{Any,1}) at ./task.jl:226
 [2] #input_convert#98(::String, ::Function, ::Dict{String,Any}, ::String) at ./task.jl:245
 [3] (::getfield(Main, Symbol("#kw##input_convert")))(::NamedTuple{(:input_file2,),Tuple{String}}, ::typeof(input_convert), ::Dict{String,Any}, ::String) at ./none:0
 [4] proc(::Dict{String,Any}) at /home/feifei/catt.jl:761
 [5] top-level scope at /home/feifei/catt.jl:823
 [6] include at ./boot.jl:326 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1038
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] exec_options(::Base.JLOptions) at ./client.jl:267
 [10] _start() at ./client.jl:436
in expression starting at /home/feifei/catt.jl:822

Any help would be greatly appreciated!

**Comment by aqzas** [comment]
Hi, JFavaloro

Path `/Users/XXX/Documents/CATT/PT1_S5_L001_R1_001.fastq` can't be reached by docker as it's an external path. So you should map the path to '/outside', the command should be like
```
docker run -it --rm -v /Users/XXX/Documents/CATT/:/output -w /output -u $UID guobioinfolab/catt \
catt --f1 PT1_S5_L001_R1_001.fastq --f2 PT1_S5_L001_R2_001.fastq -o PT1
```

**Comment by JFavaloro** [comment]
Hi aqzas,

Thank you so much for the quick response!

Unfortunately the above still gives me an error, albeit a different one now:

ERROR: LoadError: failed processes:
  Process(`/home/feifei/bwa-0.7.17/bwa mem -v 1 -t 4 -k 8 -A 1 -B 2 -L 0 -T 12 /home/feifei/resource/TR/hs/TRB/TRBV-gai6-DNA.fa PT1_S5_L001_R1_001.fastq`, ProcessSignaled(9)) [0]
  Process(`/home/feifei/samtools-1.9/samtools view -h -F 2308`, ProcessExited(1)) [1]
error(::String) at ./error.jl:33
pipeline_error(::Base.ProcessChain) at ./process.jl:803
#run#515(::Bool, ::Function, ::Base.CmdRedirect) at ./process.jl:726
run at ./process.jl:724 [inlined]
map2align(::String, ::String, ::Cmd, ::String, ::Int64, ::Int64) at /home/feifei/catt.jl:39
(::getfield(Main, Symbol("##99#101")){Dict{String,Any}})() at ./task.jl:259

...and 1 more exception(s).

Stacktrace:
 [1] sync_end(::Array{Any,1}) at ./task.jl:226
 [2] #input_convert#98(::String, ::Function, ::Dict{String,Any}, ::String) at ./task.jl:245
 [3] (::getfield(Main, Symbol("#kw##input_convert")))(::NamedTuple{(:input_file2,),Tuple{String}}, ::typeof(input_convert), ::Dict{String,Any}, ::String) at ./none:0
 [4] proc(::Dict{String,Any}) at /home/feifei/catt.jl:761
 [5] top-level scope at /home/feifei/catt.jl:823
 [6] include at ./boot.jl:326 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1038
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] exec_options(::Base.JLOptions) at ./client.jl:267
 [10] _start() at ./client.jl:436
in expression starting at /home/feifei/catt.jl:822

I'm guessing this is an error with Samtools, however (correct me if I'm wrong) the docker release should include Samtools? At any rate I believe I have the latest version installed (1.10) anyway.

As an aside, navigating to the folder containing the fastq through terminal and running the test code works as is:

docker run -it --rm -v $PWD:/output -w /output -u $UID guobioinfolab/catt \
catt -f testSample.fq -o testSampleOutput -t 2

So I tried the same thing:

docker run -it --rm -v $PWD:/output -w /output -u $UID guobioinfolab/catt \
catt --f1 PT1_S5_L001_R1_001.fastq --f2 PT1_S5_L001_R2_001.fastq -o PT1 -t 2

And got a different error:

ERROR: LoadError: failed process: Process(`/home/feifei/bwa-0.7.17/bwa mem -v 1 -t 4 -k 8 -A 1 -B 2 -L 0 -T 12 /home/feifei/resource/TR/hs/TRB/TRBV-gai6-DNA.fa PT1_S5_L001_R1_001.fastq`, ProcessSignaled(9)) [0]
error(::String, ::Base.Process, ::String, ::Int64, ::String) at ./error.jl:42
pipeline_error at ./process.jl:785 [inlined]
pipeline_error(::Base.ProcessChain) at ./process.jl:798
#run#515(::Bool, ::Function, ::Base.CmdRedirect) at ./process.jl:726
run at ./process.jl:724 [inlined]
map2align(::String, ::String, ::Cmd, ::String, ::Int64, ::Int64) at /home/feifei/catt.jl:39
(::getfield(Main, Symbol("##99#101")){Dict{String,Any}})() at ./task.jl:259
Stacktrace:
 [1] sync_end(::Array{Any,1}) at ./task.jl:226
 [2] #input_convert#98(::String, ::Function, ::Dict{String,Any}, ::String) at ./task.jl:245
 [3] (::getfield(Main, Symbol("#kw##input_convert")))(::NamedTuple{(:input_file2,),Tuple{String}}, ::typeof(input_convert), ::Dict{String,Any}, ::String) at ./none:0
 [4] proc(::Dict{String,Any}) at /home/feifei/catt.jl:761
 [5] top-level scope at /home/feifei/catt.jl:823
 [6] include at ./boot.jl:326 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1038
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] exec_options(::Base.JLOptions) at ./client.jl:267
 [10] _start() at ./client.jl:436
in expression starting at /home/feifei/catt.jl:822

No mention of a samtools error this time. Any hints?

Thanks again!

**Comment by aqzas** [comment]
Hi, JFavaloro

As you  used docker to run CATT,  the tools and packages are already set.   So I still speculated it's a path problem,  I write a mini-sample to test the command and all goes well. 

R1: `/Users/aqzas/Documents/catt/github/test_1.fastq`
R2: `/Users/aqzas/Documents/catt/github/test_2.fastq`

command: 

```Shell
docker run -it --rm -v /Users/aqzas/Documents/catt/github/:/output -w /output -u $UID guobioinfolab/catt catt --f1 test_1.fastq --f2 test_2.fastq -o test_result
```
Maybe you could figure out how to solve the problem according to the sample above.

**Comment by JFavaloro** [comment]
Hi aqzas,

Thanks again for getting back to me so quickly!

I'm not so sure it's a pathing issue (unless it's struggling to find read 2?) as the testsample example runs without issue and I'm seemingly getting the samtool error listed on the front page. Further, it is creating several *.sam files before seemingly erroring out, so it is accessing at least read 1.

Running the command you've suggested above gives me the following error:

ERROR: LoadError: failed processes:
  Process(`/home/feifei/bwa-0.7.17/bwa mem -v 1 -t 4 -k 8 -A 1 -B 2 -L 0 -T 12 /home/feifei/resource/TR/hs/TRB/TRBV-gai6-DNA.fa PT1_S5_L001_R1_001.fastq`, ProcessSignaled(9)) [0]
  Process(`/home/feifei/samtools-1.9/samtools view -h -F 2308`, ProcessExited(1)) [1]
error(::String) at ./error.jl:33
pipeline_error(::Base.ProcessChain) at ./process.jl:803
#run#515(::Bool, ::Function, ::Base.CmdRedirect) at ./process.jl:726
run at ./process.jl:724 [inlined]
map2align(::String, ::String, ::Cmd, ::String, ::Int64, ::Int64) at /home/feifei/catt.jl:39
(::getfield(Main, Symbol("##99#101")){Dict{String,Any}})() at ./task.jl:259

...and 1 more exception(s).

Stacktrace:
 [1] sync_end(::Array{Any,1}) at ./task.jl:226
 [2] #input_convert#98(::String, ::Function, ::Dict{String,Any}, ::String) at ./task.jl:245
 [3] (::getfield(Main, Symbol("#kw##input_convert")))(::NamedTuple{(:input_file2,),Tuple{String}}, ::typeof(input_convert), ::Dict{String,Any}, ::String) at ./none:0
 [4] proc(::Dict{String,Any}) at /home/feifei/catt.jl:761
 [5] top-level scope at /home/feifei/catt.jl:823
 [6] include at ./boot.jl:326 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1038
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] exec_options(::Base.JLOptions) at ./client.jl:267
 [10] _start() at ./client.jl:436
in expression starting at /home/feifei/catt.jl:822

Can I ask what in the error log suggests to you that it's a pathing error?

Thanks again!

**Comment by aqzas** [comment]
Hi, @JFavaloro 
Based on the error log, the program crash during the `bwa` process, `BWA` should be ok as it have been tested many times. After excluding the path problem, I have no idea but some assumptions about the error :

1. Do you have the write permission of folder  `/Users/XXX/Documents/CATT/` ? Otherwise CATT can't create temporary files and result files 

2. Is these two fastq files are soft links? Docker can't handle it.

3. Could you please try `bwa mem -v 1 -t 4 -k 8 -A 1 -B 2 -L 0 -T 12 /home/feifei/resource/TR/hs/TRB/TRBV-gai6-DNA.fa PT1_S5_L001_R1_001.fastq > problemfinder.sam` outside the docker to see what will happen, 'TRBV-gai6-DNA.fa' could be found in github source. If all goes well, then try 'samtools view -h -F 2308 problemfinder.sam '

**Comment by JFavaloro** [comment]
Hi aqzas,

Thanks again for the quick response and apologies for the delay in getting back to you - it took me some time to get the git release and dependencies installed (I'm still not certain I've done this correctly - this is all very new to me!)

1. Yes I have full read/write access to the folder - and again, CATT has had no problems creating the temporary files
2. No, the fastq files are in the folder, not softlinks
3. I've run the command and samtools seemingly runs through the SAM file OK - what am I looking for? There's no log file - here's a snippet of the last few lines:

M05524:59:000000000-CYR4K:1:2107:10656:3239	0	TRBV16*02	68	258S17M26S	*	0	0	AGCCCCATCTCTCAGCTGGTACACGGCAGGGTCAGGGTTCTGGATATGGGGTTTGACCATTAACCTTGTCCCCCCTCCAAAGGTGAGCATGTTGCCTGCATTATTTGCCGCTGCACAGAAGTACACTGCAGAGTCTCCAGGCTGGGAGGGCACAATGTGCAGAGAGAGGTGCTTGGCACTTTTGTTTAAGAAGACAGTGAATCTTCCATCTTCATTTTTATCCTTAATGGAACTTATAGATATCAGGAATGTAGGACCTTCAGCAGGGTATTTTTTGTACCATAGGAAATAATCAAACATG	CCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGEFFFGFFGGGGGGGGFGGFGGGFGGGFFFGFGFFGGFGFFFGFFGFFFG7	NM:i:1	MD:Z:8T8	AS:i:14	XS:i:14	SA:Z:TRBV6-6*01,75,-,175S14M112S,0,0;	XA:Z:TRBV16*03,+73,258S17M26S,1;TRBV16*01,+68,258S17M26S,1;

**Comment by aqzas** [comment]
@JFavaloro 
Honestly, I have no idea why it happens now. It seems that we have to reproduce the bug inside the docker to get full error log, try command below and see what error would happen

```
#Run docker and get inside, 
docker run -it --rm -v /Users/XXX/Documents/CATT/:/output -w /output -u $UID guobioinfolab/catt 
#Run CATT
catt --f1 PT1_S5_L001_R1_001.fastq --f2 PT1_S5_L001_R2_001.fastq -o PT1
```

**Comment by JFavaloro** [comment]
Hi aqzas,

Thanks again and apologies for the delay in getting back to you. I have run the command you have suggested and here's the output:

[ Info: 2020-07-06 00:11:48] Program start
[ Info: 2020-07-06 00:11:49] Handing Paired-end sample: PT1_S5_L001_R1_001.fastq
[ Info: 2020-07-06 00:11:49] Aligning
ERROR: LoadError: failed processes:
  Process(`/home/feifei/bwa-0.7.17/bwa mem -v 1 -t 4 -k 8 -A 1 -B 2 -L 0 -T 12 /home/feifei/resource/TR/hs/TRB/TRBV-gai6-DNA.fa PT1_S5_L001_R1_001.fastq`, ProcessSignaled(9)) [0]
  Process(`/home/feifei/samtools-1.9/samtools view -h -F 2308`, ProcessExited(1)) [1]
error(::String) at ./error.jl:33
pipeline_error(::Base.ProcessChain) at ./process.jl:803
#run#515(::Bool, ::Function, ::Base.CmdRedirect) at ./process.jl:726
run at ./process.jl:724 [inlined]
map2align(::String, ::String, ::Cmd, ::String, ::Int64, ::Int64) at /home/feifei/catt.jl:39
(::getfield(Main, Symbol("##99#101")){Dict{String,Any}})() at ./task.jl:259

...and 1 more exception(s).

Stacktrace:
 [1] sync_end(::Array{Any,1}) at ./task.jl:226
 [2] #input_convert#98(::String, ::Function, ::Dict{String,Any}, ::String) at ./task.jl:245
 [3] (::getfield(Main, Symbol("#kw##input_convert")))(::NamedTuple{(:input_file2,),Tuple{String}}, ::typeof(input_convert), ::Dict{String,Any}, ::String) at ./none:0
 [4] proc(::Dict{String,Any}) at /home/feifei/catt.jl:761
 [5] top-level scope at /home/feifei/catt.jl:823
 [6] include at ./boot.jl:326 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1038
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] exec_options(::Base.JLOptions) at ./client.jl:267
 [10] _start() at ./client.jl:436
in expression starting at /home/feifei/catt.jl:822
I have no name!@186cbe781e9c:/output$ 

The behaviour is the same; CATT seemingly runs and creates 5 files:
backup.ji - 4kb
PT1_S5_L001_R1_001.fastq.CATT.1.J.sam - 318.8MB
PT1_S5_L001_R1_001.fastq.CATT.1.V.sam - 67.1MB
PT1_S5_L001_R1_001.fastq.CATT.2.J.sam - 100.7MB
PT1_S5_L001_R1_001.fastq.CATT.2.V.sam - 8kb

I am thinking this may have something to do with the way in which we have run the sequencing, more than an issue with CATT. We have used the Takara SMARTer alpha/beta TCR kit with a MiSEQ 300x2 bp system HOWEVER as the Takara kit provides 12 unique forward i7 and one universal i5 we have run the sequencing run as if it were single indexed (i.e. not reading the i5 index). HOWEVER I have successfully used MiXCR to extract the data.

I have tried to run CATT as if it were single indexed which seemingly gives the same error.

Finally I have tried running on a different computer and running with a different input pair of fastq from the same sequencing run. All give the same Samtools error.

Any other suggestions?

Thanks again for the assistance!

**Comment by aqzas** [comment]
@JFavaloro 

Hi, JFavaloro

Sorry for the late reply.

It seems that the problem is in the samtools,  as you get the temporary sam files. But I failed to recurred the bugs any way.  I updated the samtools to version 1.10 in the CATT version 1.8.1, You can update and then try it.  I hope it could work.


```
#download the CATT 1.8.1
docker pull guobioinfolab/catt:1.8.1

#use with 1.8.1
docker run -it --rm -v /path/to/your/data:/outside -w /outside -u $UID guobioinfolab/catt:1.8.1 catt [options]
```

**Comment by JFavaloro** [comment]
Hi aqzas,

Not a problem - thanks for updating the tool. Unfortunatly I'm still getting the same error:

  Process(`/home/feifei/samtools-1.10/samtools view -h -F 2308`, ProcessExited(1)) [1]

Would you be willing to see if this is an issue with the fastq files I am using? I could upload a sample to dropbox?

Cheers

James

**Comment by aqzas** [comment]
@JFavaloro 

All right, what a weird problem : ( . 

It will be very nice of you to upload a sample to cloud storage like dropbox, helping to fix it. If the data is huge, you could just upload part of it, just ensure the upload sample could trigger the bugs

**Comment by JFavaloro** [comment]
Hi aqzas,

Great! I have emailed the team leader of the Guo lab (not sure if this is yourself) the dropbox link. If there are any issues in accessing the data please let me know!

Thanks again :)

**Comment by odonovan-brian** [comment]
bwa is crashing. Most likely because you have not allocated enough memory to your docker container.
