### ISSUE TITLE
Example output file for immunarch

### ISSUE THREAD

**Issue by vadimnazarov** [GuoBioinfoLab/CATT#6]
Hi, thank you for creating CATT, I was impressed by your benchmarks and would like to create a parser for your amazing software tool in our repository https://github.com/immunomind/immunarch Can you provide an example of the output file of CATT please?

Immunarch issue to track the parser development: immunomind/immunarch#90

Thank you so much!

Best regards,
Vadim

**Comment by aqzas** [comment]
Hello, @vadimnazarov 

Sorry for the late reply and I'm glad that Immunarch will include CATT.

The output file of CATT is in CSV format with 7 column:  `AASeq`, `NNSeq`,  `Vregion`, `Dregion`, `Jregion`, and `Prob`. The `Prob` is the possibility that the sequence exists in our reference database. I think you can ignore it in the parser.

A tiny sample is here:

[test.TRB.CDR3.CATT.csv.zip](https://github.com/GuoBioinfoLab/CATT/files/4999904/test.TRB.CDR3.CATT.csv.zip)

**Comment by vadimnazarov** [comment]
Thank you so much, it's very helpful!
